// <auto-generated />
using System;
using APBD_PROJECT.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace APBD_PROJECT.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20250629182027_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.6");

            modelBuilder.Entity("APBD_PROJECT.DataLayer.Models.Client", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CompanyName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsSoftDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Krs")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Pesel")
                        .HasMaxLength(11)
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Krs")
                        .IsUnique();

                    b.HasIndex("Pesel")
                        .IsUnique();

                    b.ToTable("Clients");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Address = "ul. Przykładowa 1, Warszawa",
                            Email = "jan.nowak@example.com",
                            FirstName = "Jan",
                            IsSoftDeleted = false,
                            LastName = "Nowak",
                            Pesel = "85010112345",
                            Phone = "123456789"
                        },
                        new
                        {
                            Id = 2L,
                            Address = "ul. Firmowa 2, Kraków",
                            CompanyName = "Example Company",
                            Email = "contact@example.com",
                            IsSoftDeleted = false,
                            Krs = "0000123456",
                            Phone = "987654321"
                        });
                });

            modelBuilder.Entity("APBD_PROJECT.DataLayer.Models.Contract", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("ClientId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsSigned")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long>("SoftwareVersionId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("SupportYears")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("SoftwareVersionId");

                    b.ToTable("Contracts");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            ClientId = 1L,
                            EndDate = new DateTime(2025, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsSigned = true,
                            Price = 1000m,
                            SoftwareVersionId = 1L,
                            StartDate = new DateTime(2025, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SupportYears = 1
                        });
                });

            modelBuilder.Entity("APBD_PROJECT.DataLayer.Models.Discount", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AppliesTo")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DiscountType")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Percentage")
                        .HasPrecision(5, 2)
                        .HasColumnType("TEXT");

                    b.Property<long?>("SoftwareId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SoftwareId");

                    b.ToTable("Discounts");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            AppliesTo = 1,
                            DiscountType = 0,
                            EndDate = new DateTime(2026, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Test Discount",
                            Percentage = 10m,
                            SoftwareId = 1L,
                            StartDate = new DateTime(2025, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("APBD_PROJECT.DataLayer.Models.Employee", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            PasswordHash = "hash",
                            Role = 1,
                            Username = "testuser"
                        });
                });

            modelBuilder.Entity("APBD_PROJECT.DataLayer.Models.Payment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long>("ContractId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ContractId");

                    b.ToTable("Payments");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Amount = 1000m,
                            ContractId = 1L,
                            PaymentDate = new DateTime(2025, 5, 27, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("APBD_PROJECT.DataLayer.Models.Software", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Software");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Category = "Utilities",
                            Description = "A test software",
                            Name = "Test Software"
                        },
                        new
                        {
                            Id = 2L,
                            Category = "Finance",
                            Description = "Comprehensive accounting software for small businesses",
                            Name = "Accounting Suite"
                        },
                        new
                        {
                            Id = 3L,
                            Category = "Productivity",
                            Description = "Tool for tracking and managing project tasks",
                            Name = "Project Manager"
                        });
                });

            modelBuilder.Entity("APBD_PROJECT.DataLayer.Models.SoftwareVersion", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("SoftwareId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("YearlyPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SoftwareId");

                    b.ToTable("SoftwareVersions");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            SoftwareId = 1L,
                            Version = "1.0.0",
                            YearlyPrice = 100m
                        });
                });

            modelBuilder.Entity("APBD_PROJECT.DataLayer.Models.Subscription", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("ClientId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("RenewalPeriod")
                        .HasColumnType("INTEGER");

                    b.Property<long>("SoftwareId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("SoftwareId");

                    b.ToTable("Subscriptions");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            ClientId = 2L,
                            IsActive = true,
                            Price = 100m,
                            RenewalPeriod = 1,
                            SoftwareId = 1L,
                            StartDate = new DateTime(2025, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("APBD_PROJECT.DataLayer.Models.SubscriptionPayment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("TEXT");

                    b.Property<long>("SubscriptionId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SubscriptionId");

                    b.ToTable("SubscriptionPayments");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Amount = 100m,
                            PaymentDate = new DateTime(2025, 5, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SubscriptionId = 1L
                        });
                });

            modelBuilder.Entity("ContractDiscount", b =>
                {
                    b.Property<long>("ContractId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("DiscountsId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ContractId", "DiscountsId");

                    b.HasIndex("DiscountsId");

                    b.ToTable("ContractDiscounts", (string)null);
                });

            modelBuilder.Entity("DiscountSubscription", b =>
                {
                    b.Property<long>("DiscountsId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("SubscriptionId")
                        .HasColumnType("INTEGER");

                    b.HasKey("DiscountsId", "SubscriptionId");

                    b.HasIndex("SubscriptionId");

                    b.ToTable("SubscriptionDiscounts", (string)null);
                });

            modelBuilder.Entity("APBD_PROJECT.DataLayer.Models.Contract", b =>
                {
                    b.HasOne("APBD_PROJECT.DataLayer.Models.Client", "Client")
                        .WithMany("Contracts")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("APBD_PROJECT.DataLayer.Models.SoftwareVersion", "SoftwareVersion")
                        .WithMany()
                        .HasForeignKey("SoftwareVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("SoftwareVersion");
                });

            modelBuilder.Entity("APBD_PROJECT.DataLayer.Models.Discount", b =>
                {
                    b.HasOne("APBD_PROJECT.DataLayer.Models.Software", "Software")
                        .WithMany()
                        .HasForeignKey("SoftwareId");

                    b.Navigation("Software");
                });

            modelBuilder.Entity("APBD_PROJECT.DataLayer.Models.Payment", b =>
                {
                    b.HasOne("APBD_PROJECT.DataLayer.Models.Contract", "Contract")
                        .WithMany("Payments")
                        .HasForeignKey("ContractId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contract");
                });

            modelBuilder.Entity("APBD_PROJECT.DataLayer.Models.SoftwareVersion", b =>
                {
                    b.HasOne("APBD_PROJECT.DataLayer.Models.Software", "Software")
                        .WithMany("Versions")
                        .HasForeignKey("SoftwareId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Software");
                });

            modelBuilder.Entity("APBD_PROJECT.DataLayer.Models.Subscription", b =>
                {
                    b.HasOne("APBD_PROJECT.DataLayer.Models.Client", "Client")
                        .WithMany("Subscriptions")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("APBD_PROJECT.DataLayer.Models.Software", "Software")
                        .WithMany()
                        .HasForeignKey("SoftwareId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("Software");
                });

            modelBuilder.Entity("APBD_PROJECT.DataLayer.Models.SubscriptionPayment", b =>
                {
                    b.HasOne("APBD_PROJECT.DataLayer.Models.Subscription", "Subscription")
                        .WithMany("Payments")
                        .HasForeignKey("SubscriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subscription");
                });

            modelBuilder.Entity("ContractDiscount", b =>
                {
                    b.HasOne("APBD_PROJECT.DataLayer.Models.Contract", null)
                        .WithMany()
                        .HasForeignKey("ContractId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("APBD_PROJECT.DataLayer.Models.Discount", null)
                        .WithMany()
                        .HasForeignKey("DiscountsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DiscountSubscription", b =>
                {
                    b.HasOne("APBD_PROJECT.DataLayer.Models.Discount", null)
                        .WithMany()
                        .HasForeignKey("DiscountsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("APBD_PROJECT.DataLayer.Models.Subscription", null)
                        .WithMany()
                        .HasForeignKey("SubscriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("APBD_PROJECT.DataLayer.Models.Client", b =>
                {
                    b.Navigation("Contracts");

                    b.Navigation("Subscriptions");
                });

            modelBuilder.Entity("APBD_PROJECT.DataLayer.Models.Contract", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("APBD_PROJECT.DataLayer.Models.Software", b =>
                {
                    b.Navigation("Versions");
                });

            modelBuilder.Entity("APBD_PROJECT.DataLayer.Models.Subscription", b =>
                {
                    b.Navigation("Payments");
                });
#pragma warning restore 612, 618
        }
    }
}
